services:
  comfyui-worker:
    image: jaysowen/runpod-worker-comfy:t2vfw-v0.1
    environment:
      - SERVE_API_LOCALLY=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/workspace/ComfyUI/output
      - ./data/runpod-volume:/runpod-volume